### ISSUE TITLE
Are you still active?

### ISSUE THREAD

**Issue by milovanderlinden** [sambrenner/soundboard#9]
Hello Sam Brenner,

Let me first thank you for the nice soundboard!

My question, are you still active? I have made some enhancements that I would like to merge into your master. Are you open to discuss the possibilities?

**Comment by sambrenner** [comment]
i'm here! i saw your pull request - i'll take a closer look and merge it in when i'm free in a few hours.

**Comment by milovanderlinden** [comment]
Great! This first pull request is simple, but I got more fixes that I will
bring in small portions for you to evaluate. I always make sure a pull
request matches a single issue and if no direct issue exists, I will create
them.

Have fun!

**Comment by sambrenner** [comment]
thanks milo!
